services:
  elliot:
    image: valentinschabschneider/elliot
    build: .
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      BROWSERLESS_ENDPOINT: ws://browserless:3000/chrome
      ENABLE_DASHBOARDS: true
    ports:
      - 3000:3000
    depends_on:
      - redis
      - browserless

  redis:
    platform: linux/x86_64
    image: redis:7.4-alpine


  browserless:
    platform: linux/x86_64
    ports:
      - 3001:3000
    image: ghcr.io/browserless/chrome:v2.31.0
    extra_hosts:
      - mijnhouseofskillsregioamsterdam.nl.local:host-gateway # ip van host.docker.internal
      - mijn.houseofskillsregioamsterdam.nl.local:host-gateway # ip van host.docker.internal
      - mijn.houseofskillsregiogroningen.nl.local:host-gateway # ip van host.docker.internal
      - tidr.ditwerkt.nl.local:host-gateway # ip van host.docker.internal
      - nom.ditwerkt.nl.local:host-gateway
      - greencareer.ditwerkt.nl.local:host-gateway
      - skillsinsight.ditwerkt.nl.local:host-gateway
